runtime: python
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: dist/healthy-pioneers/index.html
    upload: dist/healthy-pioneers/index.html
  - url: /
    static_dir: dist/healthy-pioneers

skip_files:
  - e2e/
  - node_module
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yml$
  - ^LICENSE
