runtime: nodejs22 # You can choose the appropriate Node.js version

entrypoint: npm start

instance_class: F2

handlers:
  - url: /(?:.*)
    static_files: dist/angular-ecommerce/index.html
    upload: dist/angular-ecommerce/index.html
  - url: /.*
    static_dir: dist/angular-ecommerce
