steps:
  #install node package
  - name: 'ghrc.io/cloud-builders/npm'
    args: ['install']

  #build productive files
  - name: 'ghrc.io/cloud-builders/npm'
    args: ['run','build','--prod']

  #deploy to google cloud app engine
  - name: 'ghrc.io/cloud-builders/gcloud'
    args: ['app','deploy','--version=prod']

options:
  logging: CLOUD_LOGGING_ONLY
